apiVersion: apps/v1
kind: Deployment
metadata:
  name: brideng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brideng
  template:
    metadata:
      labels:
        app: brideng
    spec:
      containers:
      - image: okteto.dev/brideng:latest
        name: brideng
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8c0d3a81-51b4-4900-b9c3-04d3731ce782"
        - name: Vless_Path
          value: "/vl379f555"
        - name: Vmess_UUID
          value: "8c0d3a81-51b4-4900-b9c3-04d3731ce782"
        - name: Vmess_Path
          value: "/vmli9rr666"
        - name: Share_Path
          value: "/v2link"
